# Generated by Django 4.2.19 on 2025-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborder',
            name='patient',
        ),
        migrations.AddField(
            model_name='laborder',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laborder',
            name='department',
            field=models.CharField(default='GWH', max_length=255),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ip_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient_name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='laborder',
            name='unit',
            field=models.CharField(default='OTHER', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
