# Generated by Django 4.2.19 on 2025-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_laborder_patient_laborder_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='privilege',
            field=models.CharField(choices=[('intern', 'Intern'), ('postgraduate', 'Postgraduate'), ('staff', 'Staff')], default='intern', max_length=50),
        ),
    ]
