# Generated by Django 4.2.19 on 2025-02-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_labtest_privilege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='price',
        ),
    ]
