# Generated by Django 4.2.19 on 2025-02-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_labtest_description_remove_labtest_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='privilege',
        ),
        migrations.AddField(
            model_name='labtest',
            name='privilege',
            field=models.ManyToManyField(related_name='tests', to='orders.privilege'),
        ),
    ]
