# Generated by Django 4.2.19 on 2025-02-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_add_privilege_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='vac_col',
            field=models.CharField(default='', max_length=255),
        ),
    ]
