# Generated by Django 4.2.19 on 2025-02-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_labtest_vac_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='name',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
