# Generated by Django 4.2.19 on 2025-02-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_labtest_privilege_labtest_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='clinical_history',
            field=models.TextField(default=''),
        ),
    ]
