# Generated by Django 4.2.19 on 2025-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_laborder_clinical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laborder',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
