# Generated by Django 4.2.19 on 2025-02-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_laborder_role_laborder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
