# Generated by Django 4.2.19 on 2025-02-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_laborder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='ageunit',
            field=models.CharField(choices=[('y', 'Years'), ('m', 'Months'), ('d', 'Days')], db_index=True, default='y', max_length=1),
        ),
        migrations.AddField(
            model_name='laborder',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='age',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='department',
            field=models.CharField(db_index=True, default='GWH', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='ip_number',
            field=models.CharField(db_index=True, default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='order_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='patient_name',
            field=models.CharField(db_index=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='unit',
            field=models.CharField(db_index=True, default='OTHER', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
