# Generated by Django 4.2.19 on 2025-02-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_laborder_ageunit_laborder_sex_alter_laborder_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborder',
            name='clinical_history',
        ),
    ]
