# Generated by Django 4.2.19 on 2025-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_laborder_clinical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='clinical_history',
            field=models.TextField(default=''),
        ),
    ]
