# Generated by Django 4.2.19 on 2025-03-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_laborder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tests', to='orders.labtest'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='section',
            field=models.CharField(default='', max_length=255),
        ),
    ]
