# Generated by Django 4.2.19 on 2025-03-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_labtest_comp_labtest_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='lab_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
