# Generated by Django 4.2.19 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_laborder_lab_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=50),
        ),
    ]
