# Generated by Django 4.2.19 on 2025-03-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_laborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='all_tests_status',
            field=models.BooleanField(default=True, help_text='Indicates if the status applies to all tests'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ipop',
            field=models.CharField(choices=[('ip', 'Inpatient'), ('op', 'Outpatient')], db_index=True, default='ip', max_length=2),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('billing', 'Billing'), ('rejected_from_lab', 'Rejected From Lab')], db_index=True, default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('billing', 'Billing'), ('rejected_from_lab', 'Rejected From Lab')], default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_statuses', to='orders.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.labtest')),
            ],
            options={
                'verbose_name_plural': 'Test Statuses',
                'unique_together': {('order', 'test')},
            },
        ),
        migrations.CreateModel(
            name='LabComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.laborder')),
            ],
            options={
                'verbose_name': 'Lab Comment',
                'verbose_name_plural': 'Lab Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='teststatus',
            field=models.ManyToManyField(related_name='status_orders', through='orders.TestStatus', to='orders.labtest'),
        ),
    ]
