# Generated by Django 4.2.19 on 2025-03-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_designation_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
