# Generated by Django 4.2.19 on 2025-02-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
    ]
